### ISSUE TITLE
请问下我使用qwen2.5-7b-insturct跑为啥总报ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by renllll** [spirit-moon-fly/CAL#2]
报错信息如下
Traceback (most recent call last):
  File "/mnt/network_share/任意/研究/BiasAsker-master/deepseek_g/偏见缓解/CAL-master/biasdetect/test_negative.py", line 16, in &lt;module&gt;
    inf.inference()
  File "/home/remotesense/anaconda3/envs/vllm/lib/python3.10/site-packages/autobiasdetector/Inference.py", line 159, in inference
    example['gold_score']=total_scores[pred].item()/total_scores[self.dataset.label_space.index(gt)].item()
ZeroDivisionError: float division by zero

**Comment by spirit-moon-fly** [comment]
这应该是由于使用LLM的不同，输出gold answer对应的第一个token时概率变为0了。对于不同的LLM，由于训练数据不同，对于相同的prompt输出格式也会不同，比如对于一个prompt，llama输出格式可能直接就是'答案'，对于其他LLM输出可能倾向于会是'The answer is 答案.' 这个时候就需要把The answer is也作为prompt的一部分拼接到原始prompt的后面才能有效地计算答案的概率
